### ISSUE TITLE
Kuadrant operator fails due to flag provided but not defined: -leader-elect

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#102]
Latest Kuadrant operator (`quay.io/kuadrant/kuadrant-operator-catalog@sha256:4425f021369a357b2b145b85f83f8f6d17c7d230de95e07243839b95c2b77884`) through OLM fails with
```
{"level":"info","ts":1668437358.5749674,"logger":"kuadrant-operator","msg":"go version: go1.18.8"}
{"level":"info","ts":1668437358.5750809,"logger":"kuadrant-operator","msg":"go os/arch: linux/amd64"}
{"level":"info","ts":1668437358.5751164,"logger":"kuadrant-operator","msg":"base logger","log level":"info","log mode":"production"}
flag provided but not defined: -leader-elect
Usage of /manager:
  -config string
    	The operator will load its initial configuration from this file. Omit this flag to use the default configuration values. Command-line flags override configuration from this file.
  -kubeconfig string
    	Paths to a kubeconfig. Only required if out-of-cluster.
```

**Comment by eguzki** [comment]
@pehala Can you test again? I cannot reproduce. 

 @didierofrivia implemented #105 for the `OSSM` branch.
I have a [WIP PR](https://github.com/Kuadrant/kuadrant-operator/pull/107) to migrate to the new catalog format (file based catalog). The branch name is `local-catalog-file-based`. I think either of those two branches should work and do not have any issue with the leader election flags.

**Comment by pehala** [comment]
The OSSM branch does indeed fix this issue

**Comment by eguzki** [comment]
:+1:  If it is not big effort, can you try `local-catalog-file-based` ?? that will be the way we create local dev testing catalogs in main
