### ISSUE TITLE
After deleting HTTPRoute, AuthorizationPolicy is still present

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#124]
Current behaviour:
If you delete HTTPRoute and have bound AuthPolicy to it, it will still route those requests to the Authorino.

Expected behaviour:
On deletion of HTTPRoute, the AuthPolicy is also invalidated, and all resources created for it will disappear.

**Comment by azgabur** [comment]
Manually tested deletion of HTTPRoute. The AuthorizationPolicy gets deleted with it and requests stop routing to Authorino returning 404.
