### ISSUE TITLE
RateLimitPolicy cleanup fails when the HTTPRoute is missing

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/kuadrant-operator#138]
A few places in the code known to fail when the target HTTPRoute is missing, instead of properly cleaning up/setting the status of policy:

1. `controllers.RateLimitPolicyReconciler.validateRuleHosts`
https://github.com/Kuadrant/kuadrant-operator/blob/fa824534a0d53d8ab6c45cbcdc8cac09489d5498/controllers/ratelimitpolicy_controller.go#L203-L206

2. `reconcilers.ReconcileTargetBackReference`
https://github.com/Kuadrant/kuadrant-operator/blob/fa824534a0d53d8ab6c45cbcdc8cac09489d5498/pkg/reconcilers/targetref_reconciler.go#L179-L183

3. `reconcilers.ComputeGatewayDiffs` - see https://github.com/Kuadrant/kuadrant-operator/pull/134#discussion_r1069308944
https://github.com/Kuadrant/kuadrant-operator/blob/fa824534a0d53d8ab6c45cbcdc8cac09489d5498/pkg/reconcilers/targetref_reconciler.go#L251-L254

---

Possibly duplicate of #125

**Comment by jsmolar** [comment]
Automation is not required.
