### ISSUE TITLE
Wrong workload selector of resources configuring a gateway

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/kuadrant-operator#141]
Some Istio resources like WasmPlugin, EnvoyFilter and AuthorizationPolicy have a workload selector to define which gateways they should apply to. The current implementation is applying Gateway API0's Gateway labels instead of workload (pod) labels on the best case or none which apply for all gateways in the same namespace.

For Authorization policy
```go
authPolicy := secv1beta1resources.AuthorizationPolicy{                                                                                                                          
    Spec: secv1beta1types.AuthorizationPolicy{                                              
        ....                                                                            
        Selector: &v1beta1.WorkloadSelector{                                                
            MatchLabels: map[string]string{}, // TODO(rahulanand16nov): fetch from gateway  
        },                                                                                  
        ...                                                     
    },                                                                                      

```

For WasmPlugins

```go
wasmPlugin := &istioclientgoextensionv1alpha1.WasmPlugin{                                                                     
    Spec: istioextensionsv1alpha1.WasmPlugin{          
        ...                                       
        Selector: &istiotypev1beta1.WorkloadSelector{                                         
            MatchLabels: gw.Labels,         // gw being the Gateway API's Gateway object                                                  
        },                                                                                                           
    },                                                                                        
}                                                                                             

```
The controller needs to read workload labels to apply correctly the selector.

Dev notes:
One possible solution worth investigating is reading Gateway `status.addresses` object

```yaml
status:
  addresses:
    - type: Hostname
      value: istio-ingressgateway.istio-system.svc.cluster.local:80
```
that gives the service, and inspecting the service, there is a `spec.selector`. Getting the pods in that namespace with that `spec.selector` will give the list of workload pods, and reading any of those pods will give the labels needed to configure the Istio resources.

**Comment by guicassolato** [comment]
@eguzki ,

I like the proposed approach based on the `Service`'s `selector`. Two minor questions to refine it:

1. After reading the `Service`'s `spec.selector`, do we still need the extra step of reading the pod? If I understand correctly, `services.spec.selector` determines already [the set of pods targeted by the service](https://kubernetes.io/docs/concepts/services-networking/service/#service-resource), which matches the definition of Istio's [Workload Selector](https://istio.io/latest/docs/reference/config/type/workload-selector/#WorkloadSelector). Won't just reading the service suffice then?
2. Probably really an edge case, but I imagine we wouldn't support [services without selectors](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors). IMO, going any deeper than the layer of the service seems a bit overkill for the reconciliation. WDYT?

**Comment by eguzki** [comment]
> After reading the Service's spec.selector, do we still need the extra step of reading the pod? If I understand correctly, services.spec.selector determines already [the set of pods targeted by the service](https://kubernetes.io/docs/concepts/services-networking/service/#service-resource), which matches the definition of Istio's [Workload Selector](https://istio.io/latest/docs/reference/config/type/workload-selector/#WorkloadSelector). Won't just reading the service suffice then?

For the first implementation it can be enough. I was thinking on the selector being, for instance `a: 1, b: 2` and the pod having  `a: 1, b: 2, c: 3`

> Probably really an edge case, but I imagine we wouldn't support [services without selectors](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors). IMO, going any deeper than the layer of the service seems a bit overkill for the reconciliation. WDYT?

Good point, but I do not think that applies to Istio, but we do not know what other providers may do. We cannot even be sure if the `type: Hostname` will be there poiting to a service. It could be an IP.  It is also true that for other providers kuadrant may not need to find out workload labels (attaching resources might be implemented with direct refs instead of label selectors). 

For me, ideally, kuadrant knowing that the gateway provider is Istio, kuadrant should ask Istio for that info.
