### ISSUE TITLE
Local kind fails to create a cluster

### ISSUE THREAD

**Issue by didierofrivia** [Kuadrant/kuadrant-operator#151]
When running the `make local-setup` target, an error is raised informing the following:

```sh
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kuadrant-local-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I0314 16:30:42.135126     143 initconfiguration.go:247] loading configuration from "/kind/kubeadm.conf"
```

Local environment:
* OS/Arch: Fedora 37 amd64
* docker: 23.0.1
* golang 1.19.6
* kubectl client: v1.26.2
* kubeadm: v1.26.2

Steps to reproduce:
1. Checkout kuadrant-operator
2. run `make local-setup` 

Notes:
We might be hitting the same issue here https://github.com/kubernetes-sigs/kind/issues/2156

**Comment by eguzki** [comment]
can you try @didierofrivia with the `latest`? If it does, we can close this issue
