### ISSUE TITLE
Support MGC requirements to configure Redis' URL for limitador

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/kuadrant-operator#163]
This is possibly impacting #164

**Comment by alexsnaps** [comment]
@maleck13 Did you have something on this already? i.e. how would Kuadrant's Limitador server be configured to use the Elasticache instance?

**Comment by maleck13** [comment]
No I think we just worked around it by configuring redis in limitador directly cc @R-Lawton. 
I guess if installing kuadrant the question is whether we expose it from the kuadrant CR or not. My thoughts would be that we use a secret to store the connection credentials and a ref can be passed to that secret in the kuadrant cr?

**Comment by alexsnaps** [comment]
We're currently pondering multiple options, as discussed in the [weekly meeting](https://docs.google.com/document/d/1zLL01Sdp6w2zV1fHPLKv94UwXPAKG_V56zKMc3oJttM/edit#heading=h.uvkbhurqx0ry) (see Petr's item). @eguzki will start with #164 to address this "in its entirety", but start with this bit. So that this issue will _try_ to have the parts of the full solution for MGC to use… hopefully - so whatever comes out of this is to be "draft", but address the problem.

**Comment by Boomatang** [comment]
A proposed solution to this problem is outline in https://github.com/Kuadrant/architecture/pull/25, it would be good if everyone could have a look at it.
