### ISSUE TITLE
Common CI/CD workflows - investigation/planning

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#21]
**What**

- [x] Define a common set of workflows that each of our components should put in place. (look at existing ones from GLBC and Authorino etc to see what can be reused
- [x] Once agreed flows are in place define the set of tasks needed for each component and link them into this overall epic

**Comment by guicassolato** [comment]
Here are a few ideas for automated CI/CD workflows and a brief assessment of the current status of those in the Kuadrant components.

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Workflow</th>
      <th>Trigger</th>
      <th>K</th>
      <th>KO</th>
      <th>A</th>
      <th>AO</th>
      <th>L</th>
      <th>LO</th>
      <th>GLBC</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan="4"><b>A.</b> Linters & Code style</td>
      <td><b>A1.</b> Built-in auto-format<br/><sub><code>go fmt</code>, <code>go vet</code>, <code>cargo fmt</code></sub></td>
      <td>PR, merge</td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><b>A2.</b> 3rd-party linters<br/><sub><a href="https://github.com/reviewdog/reviewdog">Reviewdog</a>, <a href="https://golangci-lint.run">golangci-lint</a>, <a href="https://github.com/Manishearth/rust-clippy">Clippy</a> - Trailing whitespaces, EOF newline, Language-specific</sub></td>
      <td>PR, merge</td>
      <td>&check;</td>
      <td></td>
      <td>&check;</td>
      <td></td>
      <td></td>
      <td></td>
      <td>&check;</td>
    </tr>
    <tr>
      <td><b>A3.</b> Misspelling<br/><sub><a href="https://github.com/client9/misspell">client9/misspell</a></sub></td>
      <td>PR, merge</td>
      <td>&check;</td>
      <td></td>
      <td>&check;</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><b>A4.</b> Language<br/><sub><a href="https://github.com/get-woke/woke">Woke</a></sub></td>
      <td>PR, merge</td>
      <td>&check;</td>
      <td></td>
      <td>&check;</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="4"><b>B.</b> Tests<br/></td>
      <td><b>B1.</b> Unit tests<br/><sub><code>go test</code>, <code>cargo test</code></sub></td>
      <td>PR, merge</td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;</td>
    </tr>
    <tr>
      <td><b>B2.</b> End-to-end tests<br/><sub>Build an image → deploy → run integration tests</sub></td>
      <td>Merge, manual</td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;</td>
      <td></td>
      <td></td>
      <td></td>
      <td>&check;</td>
    </tr>
    <tr>
      <td><b>B3.</b> Smoke tests<br/><sub>Deploy image from <a href="https://quay.io/organization/kuadrant">quay.io/kuadrant</a> → run integration tests</sub></td>
      <td>After C1</td>
      <td></td>
      <td></td>
      <td>&check;</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><b>B4.</b> Performance & Benchmarks</td>
      <td>After C1</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>&check;<sup>1</sup></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="2"><b>C.</b> CI/CD</td>
      <td><b>C1.</b> Build and push image to <a href="https://quay.io/organization/kuadrant">quay.io/kuadrant</a></td>
      <td>Merge</td>
      <td>&check;<sup>2</sup></td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;</td>
      <td>&check;<sup>2</sup></td>
      <td>&check;</td>
      <td>&check;</td>
    </tr>
    <tr>
      <td><b>C2.</b> Deploy<br/><sub>Shared Kubernetes/OpenShift cluster in the cloud</sub></td>
      <td>After B3, manual</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="5"><b>D.</b> Code scan<br/><sub>(vulnerability, dependency updates)</sub></td>
      <td><b>D1.</b> <a href="https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts">Dependabot alerts</a><sup>3</sup></td>
      <td>Daily</td>
      <td>&check;</td>
      <td></td>
      <td>&check;</td>
      <td></td>
      <td>&check;</td>
      <td></td>
      <td>&check;</td>
    </tr>
    <tr>
      <td><b>D2.</b> <a href="https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates">Dependabot version updates</a><sup>3</sup></td>
      <td>Daily</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><b>D3.</b> <a href="https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-dependabot-security-updates">Dependabot security updates</a><sup>3</sup></td>
      <td>Daily</td>
      <td>&check;</td>
      <td></td>
      <td>&check;</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><b>D4.</b> Code vulnerability scan<br/><sub><a href="https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning">CodeQL</a><sup>3</sup>, <a href="https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics">Red Hat Dependency Analytics</a><sup>4</sup></sub></td>
      <td>Daily</td>
      <td>&check;</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><b>D5.</b> Static Code Analysis<br/><sub><a href="https://www.sonarqube.org/">SonarQube</a><sup>5</sup></sub></td>
      <td>Daily</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="4"><b>E.</b> Badges</td>
      <td><b>E1.</b> Test status & coverage</td>
      <td>Merge</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><b>E2.</b> Code analysis (dependencies, security)</td>
      <td>After D4-5</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<sup>K</sup> [Kuadrant](https://github.com/kuadrant/kuadrant-controller)
<sup>KO</sup> [Kuadrant Operator](https://github.com/kuadrant/kuadrant-operator)
<sup>A</sup> [Authorino](https://github.com/kuadrant/authorino)
<sup>AO</sup> [Authorino Operator](https://github.com/kuadrant/authorino-operator)
<sup>L</sup> [Limitador](https://github.com/kuadrant/limitador)
<sup>LO</sup> [Limitador Operator](https://github.com/kuadrant/limitador-operator)
<sup>GLBC</sup> [Global Load Balancer Controller](https://github.com/Kuadrant/kcp-glbc)

<sup>1</sup> Currently set to trigger at every push (PR, merge)
<sup>2</sup> Currently configured in Quay instead of GHA
<sup>3</sup> Configurable in GitHub (Repo > Settings > Code security and analysis)
<sup>4</sup> Run as a Visual Studio Code extension
<sup>5</sup> Red Hat provides it for internal use; likely not suitable for the upstream

**Comment by maleck13** [comment]
@guicassolato thanks this is a great visual aid. With C2 the GLBC does have this, it also will very shortly have b4 (pr open)

**Comment by guicassolato** [comment]
> With C2 the GLBC does have this

@maleck13, I saw https://github.com/Kuadrant/kcp-glbc/blob/4a3b8a8c111f66adc5991d14692a940affe16c49/.github/workflows/kcp-glbc-image.yaml#L66. However, this one does not deploy to a shared cluster – or shared clusters (plural), in the case of GLBC. I was thinking on an env where we (engineers), but also QEs and PMs could all log in and try the deployment afterwards. Or maybe you meant some other workflow/step of the GLBC repo?

> it also will very shortly have b4 (pr open)

Updated in the table. Thanks!

**Comment by maleck13** [comment]
It is deployed to a cluster and integrates with a KCP where it could be accessed and used.

**Comment by didierofrivia** [comment]
Would it make sense to also include automated release? 

Like so:
<table>
    <tr>
      <td rowspan="2"><b>D.</b> Release</td>
      <td><b>D1.</b> Tag</td>
      <td>Manual</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td><b>D2.</b> Version</td>
      <td>Manual</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

**Comment by guicassolato** [comment]
@didierofrivia 

> Would it make sense to also include automated release?

Assuming you mean releases to the upstream of course...

Main problem with automating the release is writing the change log, but I guess that could be an input field of the workflow dispatch form? Though it's not as rich text editing as GitHub's release notes editor.

Apart from the release notes, in the operands, releasing essentially consists of picking a Git SHA and assigning a version to it. It's easy.

The operators, on the other hand, usually involve pairing with released versions of the operands', plus modifying a few internals in the code and committing the changes to a release branch. Still doable though.

We have the (manual) release process documented for Authorino.
