### ISSUE TITLE
Automate adding created issues to the kuadrant service protection project

### ISSUE THREAD

**Issue by KevFan** [Kuadrant/kuadrant-operator#222]
It was mentioned that issues need be to in the correct project to be visible during refinement.

Github allows adding workflows to automatically add items to a project:
- https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/adding-items-automatically

Created issues from the following should be added to the `Kuadrant Service Protection` Project automatically so that issues are not lost / forgotten when viewing the project board for refinement:
- Kuadrant Operator
- Limitador Operator
- Limitador
- Authorino Operator
- Authorino

This issue can be used to track this work

**Comment by adam-cattermole** [comment]
Looking at the Project settings it is only possible to add a filter for a single project in it's own auto-add workflow and this is limited by plan so by the looks of things we can only auto-add issues from a single repository with GitHub Free.

 As an alternative [this action](https://github.com/actions/add-to-project) looks like it might do what we need and can be configured from each of the repositories.

**Comment by adam-cattermole** [comment]
The action I linked above actually requires a Personal Access Token (with `project` + `repo` scopes) as it does not appear you can set up organisation level access tokens. I think this means all issues will appear to be added by one of our user accounts and that our personal access token would be set in several repositories or at the organisation level which I'm not 100% we should be doing.

**Comment by adam-cattermole** [comment]
@alexsnaps has brought [@kuadrant-dev](https://github.com/kuadrant-dev) to our attention so we'll look at using this to configure the workflows.

**Comment by adam-cattermole** [comment]
The PR's are draft-ready and just need an organisation level secret to be added to be functional.

However the @kuadrant-dev account does not meet the prerequisites to join the @Kuadrant org to enable creation of the token.

**Comment by adam-cattermole** [comment]
Closing as done, the PR's for each of the repos are merged and the action has successfully run to add issues to the project.
