### ISSUE TITLE
tool: upgrade to go 1.20

### ISSUE THREAD

**Issue by KevFan** [Kuadrant/kuadrant-operator#236]
As a pre-req to https://github.com/Kuadrant/kuadrant-operator/issues/203, we should upgrade to Go 1.20

Things to consider on this upgrade:
* Workflows should be updated to this version
* Consider any functions that can be simplified from new functions natively provided by Go 1.20
* Any go.mod / go.sum changes

**Comment by KevFan** [comment]
@guicassolato do you have any thoughts on whether we want to use the experimental slices package (https://pkg.go.dev/golang.org/x/exp@v0.0.0-20230817173708-d852ddb80c63/slices) to remove / simplify https://github.com/Kuadrant/kuadrant-operator/blob/main/pkg/common/common.go#L92-L189

This slice package is provided as part of Go 1.21 standard library https://pkg.go.dev/slices@go1.21.0 but is not available in Go 1.20

**Comment by guicassolato** [comment]
> @guicassolato do you have any thoughts on whether we want to use the experimental slices package

It's a shame it doesn't include a few generic functions we depend on (e.g. [`common.Map`](https://github.com/Kuadrant/kuadrant-operator/blob/6f3b3fdee2d0213da3331265e14e72a2523cba4f/pkg/common/common.go#L151), [`common.Filter`](https://github.com/Kuadrant/kuadrant-operator/blob/6f3b3fdee2d0213da3331265e14e72a2523cba4f/pkg/common/common.go#L160), [`common.Intersect`](https://github.com/Kuadrant/kuadrant-operator/blob/6f3b3fdee2d0213da3331265e14e72a2523cba4f/pkg/common/common.go#L104), [`common.Intersection`](https://github.com/Kuadrant/kuadrant-operator/blob/6f3b3fdee2d0213da3331265e14e72a2523cba4f/pkg/common/common.go#L125C6-L125C18)), but many others are there. So let's use it!
