### ISSUE TITLE
Update Service Protection Install guide to reflect channel override changes

### ISSUE THREAD

**Issue by jsmolar** [Kuadrant/kuadrant-operator#269]
Service Protection Install guide  https://github.com/Kuadrant/multicluster-gateway-controller/pull/617

Update the command for Manage Cluster addon annotation:
```oc annotate managedclusteraddon kuadrant-addon "addon.open-cluster-management.io/values"='{"CatalogSourceNS":"openshift-marketplace",  "CatalogSource":"community-operators", "Channel":"preview"}' -n managed-cluster-ns```

**Comment by maleck13** [comment]
https://github.com/Kuadrant/multicluster-gateway-controller/pull/724
