### ISSUE TITLE
AuthPolicy status

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/kuadrant-operator#290]
- [x] Implementation of [RFC 0004](https://github.com/Kuadrant/architecture/blob/main/rfcs/0004-policy-status.md) for the AuthPolicy
- [ ] #690
  - Maybe a list of auth rules by name that will apply to which HTTPRouteRule (?)

**Comment by KevFan** [comment]
@guicassolato for task 2, it seems like there is some description missing "Update the status stanza of the AuthPolicy about route selectors that failed to" 🤔

**Comment by guicassolato** [comment]
> @guicassolato for task 2, it seems like there is some description missing "Update the status stanza of the AuthPolicy about route selectors that failed to" 🤔

Thanks @KevFan. Updated the description.

**Comment by guicassolato** [comment]
Extracted the detail into a separate issue so this one can be closed as done
