### ISSUE TITLE
Deprecate workload selectors?

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/kuadrant-operator#302]
I think with this being introduced in [Istio 1.20](https://istio.io/latest/news/releases/1.20.x/announcing-1.20)

>In this release, we have also added support for configuring Istio CRDs `AuthorizationPolicy`, `RequestAuthentication`, `Telemetry` and `WasmPlugin `for Kubernetes Gateway API via the `targetRef` field.

We might be able to leverage `targetRef`'ing the `Gateway` directly in our code just as well.

**Comment by KevFan** [comment]
`WasmPlugin` has been updated to use `targetRef` as part of https://github.com/Kuadrant/kuadrant-operator/pull/612/files

Similar can be done to `AuthorizationPolicy` at:
https://github.com/Kuadrant/kuadrant-operator/blob/6823ed0d0f5be18d358d8f68163096c240366670/controllers/authpolicy_istio_authorizationpolicy.go#L90-L105
