### ISSUE TITLE
Kuadrant Operator is crashing when installed via addon manager

### ISSUE THREAD

**Issue by jsmolar** [Kuadrant/kuadrant-operator#332]
When Kuadrant is installed via addon manager using weekly build: https://quay.io/kuadrant/kuadrant-operator-catalog:aebe2ec63e1bfad0f391c329a9c9f6ede36086d9
The Kuadrant Operator is caught in the endless cracking loop (keeps changing status from Succeeded and Installing). 
Two pods are on CrashLoopBackOffs:

- kuadrant-operator-controller-manager - 
[kuadrant-operator-controller-manager-5f54f695b-mlk7n-manager.log](https://github.com/Kuadrant/kuadrant-operator/files/13449074/kuadrant-operator-controller-manager-5f54f695b-mlk7n-manager.log)

- kuadrant-operator-policy-controller - 
[kuadrant-operator-policy-controller-5ff6ddc9c8-djbdn-policy-controller.log](https://github.com/Kuadrant/kuadrant-operator/files/13449077/kuadrant-operator-policy-controller-5ff6ddc9c8-djbdn-policy-controller.log)

Short slack communication: https://kubernetes.slack.com/archives/C05J0D0V525/p1700661805580859

**Comment by pehala** [comment]
Based on the logs, I believe it is caused by us having older GW API version. Will verify and resolve this issue if that is indeed the case.

**Comment by alexsnaps** [comment]
To be verified... looks like a GwAPI types version issue possibly

**Comment by pehala** [comment]
It was indeed issue of an older GW API
