### ISSUE TITLE
Development environment (spawned with `make local-setup`) does not support `targetRef` in the wasmplugin object. 

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/kuadrant-operator#342]
Motivated by the deprecation of workload selectors on the issue #302, we found an [Istio issue](https://github.com/istio/istio/issues/48026) on using  the `targetRef` of the wasmpluging when the targeted gateway is `istio-ingressgateway` (or any [manually deployed](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment) Gateway API gateway). Thus, currently, our development environment (spawned with `make local-setup`) does not support `targetRef` in the wasmplugin object. 

Istio engineers provided a workaround, but clearly stated that it was intended not to apply to Istio ingress gateway. 

So, there are three ways we can take in order to deprecate workload selectors with `targetRef`:

* Replace istio-ingressgateway with automatically deployed Gateway
> **Note**: Sometimes it is very handy to switch Envoy's log level to `debug` to see what decisions are being maked at the gateway level regarding auth and rate limiting filters. For the istio-ingressgateway, it is just about `k edit deployments istio-ingressgateway -n istio-system` and then `set "--proxyLogLevel=debug"`. However, for automatically deployed Gateways, the deployment is fully reconciled and modifications of the log level are not allowed.
* Investigate the workaround provided in the [Istio issue](https://github.com/istio/istio/issues/48026#issuecomment-1826046970) and keep using Istio ingress gateway. 
* Postpone the replacement of the workload selectors with the targetRef and wait for Istio to fix it (if they ever decide to fix it). 

PS: My take is to go for the first one, i.e. use an automatically deployed gateway. Some of the Istio design decisions regarding Gateway API on-boarding are explicitly avoiding Istio ingress gateway, and more issue may happen in the future like this one. Postponing does not seem a good option as well IMO. The `targetRef` is clearly a simplification that can benefit the users of kuadrant and does not seem fair to block it because there is an issue with out development environment.

**Comment by alexsnaps** [comment]
@adam-cattermole that's what I was talking about

**Comment by alexsnaps** [comment]
#298 did:
>Replace istio-ingressgateway with automatically deployed Gateway
