### ISSUE TITLE
Rate Limit Policy status "HTTPRoute is ratelimited" is misleading

### ISSUE THREAD

**Issue by jsmolar** [Kuadrant/kuadrant-operator#406]
When RLP is applied, but not protecting any HTTPRoute, the status is `HTTPRoute is ratelimited`. This is not true in some cases. E.g. when there is no matching HTTPRoute rule for the limit.

Proposed change:
`HTTPRoute is ratelimited` to `Policy is enabled`

**Comment by KevFan** [comment]
This is addressed by https://github.com/Kuadrant/kuadrant-operator/pull/347

**Comment by KevFan** [comment]
Closing as addressed by https://github.com/Kuadrant/kuadrant-operator/pull/347, which will be included in the next Kuadrant Operator release
