### ISSUE TITLE
Test plan/script to ensure example dashboards and alerts work with a specified version (or min/max version) of Grafana & Prometheus

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/kuadrant-operator#443]
- dashboards & graphs probably tested manually
- setup of cluster with dashboards & alerts loaded into it can be automated (bash is fine)

**Comment by azgabur** [comment]
I will be asking ServiceMesh and Graphana dev/qe team to see if they test the dashboards other way than just by manual testing. Will come back to this.

**Comment by david-martin** [comment]
Thanks @azgabur.
If there's any update, can you add it to the automation issue https://github.com/Kuadrant/kuadrant-operator/issues/444 instead?
I'm going to close this issue, but keep the issue for automating as I think there's more value in landing the automation as part of a github action from the start.
