### ISSUE TITLE
Add a GH action for deploying and verifying dashboards & alerts load OK with quickstart

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/kuadrant-operator#444]
Testing will be automated & deploys the dashboards & alerts somewhere.
Suggesting a github action that runs if dashboard or alert files change.
See comment [here](https://github.com/Kuadrant/testsuite/issues/401#issuecomment-2126918010) for suggestion on APIs to confirm dashboards and alerts have loaded ok.

**Comment by ehearneRedHat** [comment]
### Potential checklist

- [ ] Run quickstart and see what dashboards and alerts are loaded, and manually verify if they loaded in correctly.
- [ ] After verifying what a successful 'load in' looks like, investigate how to create a github action that verifies whether the current dashboard and alerts load in correctly.
  - [ ] Run quickstart and check for success message before proceeding on.
  - [ ] Once success, check for all dashboard and alerts having a 'success' status.
  - [ ] If failure, list the failed dashboard and alerts, explaining why they failed. 
  - [ ] Try to make this happen through a list that does not need to be inputted manually.
