### ISSUE TITLE
dnspolicy: Update LB CNAME generation for loadbalanced strategy  

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/kuadrant-operator#451]
Currently the Kuadrant Operator builds the LB CNAME with a guid based on the name of the gateway, as this could potentially be different on different clusters, this will need to be updated to generate based on the zone's root hostname, to ensure it is consistently generated on all clusters that interact with this zone.

currently: `lb.<gw-guid>.<root-host>`
new format: `klb.<root-host>`

**Comment by maleck13** [comment]
@philbrookes not sure if this is done or not?
