### ISSUE TITLE
dnspolicy: Aggregate DNSRecord status

### ISSUE THREAD

**Issue by philbrookes** [Kuadrant/kuadrant-operator#454]
When the DNS Operator performs actions based on the state of a DNS Record, it should update the DNS Record status with results of these actions, similar to how it is currently implemented

The kuadrant-operator should expect all of the DNS Records for a particular policy to eventually have an accepted status (see [here](https://github.com/Kuadrant/dns-operator/issues/34) for more information). Once they are all accepted, this DNS Policy should have it's status set to `enforced`.

- [ ] Add logic to aggregate status to DNS Policy
- [ ] Tests created to cover this aggregated status

**Comment by makslion** [comment]
covered in #449
