### ISSUE TITLE
Error running quickstart script when following single cluster tutorial

### ISSUE THREAD

**Issue by ehearneRedHat** [Kuadrant/kuadrant-operator#459]
# What:
Error occurs on line 122 of file `hack/quickstart-setup.sh` when opting to use AWS as DNS provider.

`bash: line 122: configureController: command not found`

Script ends prematurely.

# Why:

Script unable to get configContoller function from our multicluster-gateway-controller repository as files have been edited.

Lines 34 and 35 of the mentioned script.

```bash
source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/${KUADRANT_ORG}/multicluster-gateway-controller/${MGC_REF}/hack/.quickstartEnv)"
source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/${KUADRANT_ORG}/multicluster-gateway-controller/${MGC_REF}/hack/.deployUtils)"
```

**Comment by mikenairn** [comment]
Changes were made here https://github.com/Kuadrant/multicluster-gateway-controller/pull/789/files#diff-94a23eb675ecc703d595e64f29874ff336d9124e04059fbc465cdb4d59e8af47. Quickest fix is probably to add these back https://github.com/Kuadrant/multicluster-gateway-controller/pull/789/files#diff-94a23eb675ecc703d595e64f29874ff336d9124e04059fbc465cdb4d59e8af47L321-L429

**Comment by maleck13** [comment]
export MGC_REF=v0.3.0
export KUADRANT_REF=v0.6.1

gets further but fails with

```
Error from server (NotFound): error when creating "STDIN": namespaces "multi-cluster-gateways" not found
Error from server (NotFound): error when creating "STDIN": namespaces "multicluster-gateway-controller-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "multi-cluster-gateways" not found
```

investigating

**Comment by ehearneRedHat** [comment]
Closing issue as resolved.
