### ISSUE TITLE
Update DNSPolicy default geo logic

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/kuadrant-operator#545]
**What**

Update the default geo logic for `loadbalanced` policy types to make the creation of the default geo endpoint dependant on the current cluster existing in the desired default geo. If the there is no match the endpoint should not be added to the endpoint [list](https://github.com/Kuadrant/kuadrant-operator/blob/main/controllers/dns_helper.go#L217) .

**Why**

Currently it is assumed that we will always want the default geo to be set to something, if no cluster(s) matches the current default geo it will automatically select one that does exist. This is used primarily for route53 to ensure that a dnsName is accessible from all locations around the world. With distributed dns however, individual clusters cant be sure what the default geo should really be and should not try and be smart during the selection of it.

**How**
 
* Update tests, ensure to add a test that doesn't default geo 
* Update DNSPolicy docs to call out the behaviour 
* Set DNSPolicy default geo to required

Related:

* https://github.com/Kuadrant/dns-operator/issues/86

**Comment by maleck13** [comment]
@makslion as part of this pls ensure the DNSPolicy CRD has defaultGEO as required
