### ISSUE TITLE
Lowered limit for AuthPolicy rules section

### ISSUE THREAD

**Issue by azgabur** [Kuadrant/kuadrant-operator#566]
Due to https://github.com/Kuadrant/kuadrant-operator/pull/525 the limit for AuthPolicy rules section is now 10. This number is relatively low and has also not been officially documented. Some teams utilizing Authorino have implemented AuthConfig with up to 14 rules so I think this limit should be raised back.

The discussion slack link:
https://kubernetes.slack.com/archives/C05J0D0V525/p1713781063062309?thread_ts=1713343676.107059&cid=C05J0D0V525

**Comment by guicassolato** [comment]
I expect this to be solved as part of removing the `routeSelectors` in favour of targetRef.sectionName (#809).

Hopefully this will decrease the complexity level of the API validation, thus allowing more rules into the budget.

**Comment by guicassolato** [comment]
Fixed in #924

**Comment by jsmolar** [comment]
@guicassolato I am still seeing this in RC4

**Comment by guicassolato** [comment]
I had removed it. I guess it was added back during a rebasing. It's a bug.
