### ISSUE TITLE
Fix settings generation in tests

### ISSUE THREAD

**Issue by didierofrivia** [Kuadrant/kuadrant-operator#57]
In some integration tests we are relying on random namespace generation, which makes it hard to test dependent services expecting an ENV var value to be already setup.

**Comment by didierofrivia** [comment]
This is related to https://github.com/Kuadrant/kuadrant-operator/issues/69, since right now the flow accepting Kuadrant services installed in a custom namespace is broken

**Comment by alexsnaps** [comment]
@didierofrivia Is this still relevant?

**Comment by KevFan** [comment]
@didierofrivia can this be closed? 🤔 We have the integration tests running in parallel so not sure if this still needs to be addressed
