### ISSUE TITLE
openshift quickstart tyre kicking

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadrant-operator#573]
WHAT:
Create a quickstart that brings up a environment similar to what will be used for the ✨Demo✨ . Similar to the GitHub [action](https://github.com/Kuadrant/eng-environment/blob/main/.github/workflows/infra-deploy.yml) in the eng environment which currently brings up ingress, distributed and kuadrant pieces via argo but adding the observability, sail and SSO pieces as well.

HOW:
Create a script using ❤️bash❤️  that brings up all the above pieces for both openshift environments and bare k8s environments if needed we can have env var for different options as we see fit.

**Comment by david-martin** [comment]
I've unassigned and put this back to Todo.
Priority wise, I'll be focusing on https://github.com/Kuadrant/kuadrant-operator/issues/495 at this time.

**Comment by maleck13** [comment]
I think this can be closed as out of date now?
