### ISSUE TITLE
ci: build catalog job can fail for branches with certain names

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/kuadrant-operator#580]
**What**

The Build catalog job can fail in certain cases see https://github.com/Kuadrant/kuadrant-operator/actions/runs/8831513068/job/24259023192?pr=549

Looks like it fails due to the branch name having upper case characters in it.

**Comment by KevFan** [comment]
The issue looks to be that when pushing images using branch name as tags, the pushed tag is always lowercased even though the branch name itself may have a uppercase. This causes a mismatch between the tag used by the workflow vs what is actually pushed/created in quay.io.

A possible solution to this may be to lowercase the tag input first and this this lowercased tag throughout the workflow instead. Possible ways to do this may be https://github.com/orgs/community/discussions/25768
