### ISSUE TITLE
Gateway attached Policy stays enforced after Gateway deletion

### ISSUE THREAD

**Issue by martinhesko** [Kuadrant/kuadrant-operator#588]
# Description

With a GW RLP defining defaults and a child route inheriting this RLP, After Gateway that had the RLP attached gets deleted the RLP keeps being listed as `Enforced: True` and `HTTPRoute` says it's being affected by this policy.

**Comment by martinhesko** [comment]
Same problem with AuthPolicy, changed the name to be more general.

**Comment by Boomatang** [comment]
Being digging around in this a bit. The problem seems not to be related to defaults and overrides, as I believe the dns policy would have being affected by the same issue. Current work to solve the issue by removing the `Enforced` status block if the `Accepted` block is false.
