### ISSUE TITLE
DNSPolicy Gateway with wildcard listener and HttpRoute - no routes attached for listeners

### ISSUE THREAD

**Issue by ficap** [Kuadrant/kuadrant-operator#589]
When I have a Gateway with two listeners - one wildcard (\*.sub.example.com) and one classic (static.example.com) and a HttpRoute targeting wildcard listener with hostname foo.sub.example.com, DNSPolicy on the gateway is not enforced with message `'DNSPolicy has encountered some issues: policy is not enforced on any dns record: no routes attached for listeners'` even though there is attached route for wildcard listener.
When I have a Gateway with one wildcard listener (\*.sub.example.com) with attached dnspolicy and corresponding httproute foo.sub.example.com everything works ok.

**Comment by maleck13** [comment]
what is the full status @ficap is it partially enforced? @makslion seems like we could have a slightly better message if so? IE `policy is not enforced for listeners {listenerName1, listenerName2} have no attached routes`

**Comment by makslion** [comment]
the #586 would make the partially enforced messages much better

**Comment by maleck13** [comment]
@ficap can you provide a set of resources? I am failing to reproduce this at the moment

**Comment by ficap** [comment]
After further investigation we found out that the issue occurs when you use your objects but swap listeners in the gateway the first would be `app1...` and the second would be wildcard `*.apps...` in this case we were able to reproduce the issue  with 100% success.

**Comment by maleck13** [comment]
interesting. @makslion @mikenairn any thoughts on what might cause that? So more specifically, if you define a specific listener before a wildcard listener we hit this issue

**Comment by pehala** [comment]
The workaround is to set the wildcard listener first, as can be seen in above example
