### ISSUE TITLE
Limitador CR should reconcile to default values for fields that are not defiend

### ISSUE THREAD

**Issue by jsmolar** [Kuadrant/kuadrant-operator#617]
In issue [#307](https://github.com/Kuadrant/kuadrant-operator/issues/307), it was mentioned:

"The Kuadrant operator should only reconcile the spec that is given. This would mean if the user specifies the number of replicas for a component, only the replica field for that component should be reconciled. As other fields might be blank at this stage, these blank fields should not be reconciled to the component Custom Resource (CR)."

However, this behavior is incorrect. Since the subcomponent CR is managed by the Kuadrant CR, it needs to be fully managed. In the current implementation ([PR #350](https://github.com/Kuadrant/kuadrant-operator/pull/350)), blank fields are ignored, resulting in the component inconsistent behavior from the user perspective.

Example: Inconsistency arises when we have two Kuadrants, each managing a Limitador. For the same Limitador spec configuration in Kuadrant CR, we can result in two different Limitador deployments. If blank fields result in default values instead of being ignored, we can achieve consistency and reconcile only the fields that we intend to modify.

The desired behavior should be as follows: if fields are left blank, they should be reset to their default values rather than being ignored.

**Comment by eguzki** [comment]
Multiple kuadrant CRs at the same time is not supported as of today

The reconciliation pattern is being refactored in https://github.com/Kuadrant/kuadrant-operator/pull/608, however, the approach does not change. Only fields specified in the kuadrant CR will be enforced in the Limitaodr CR. Any field not defined in kuadrant CR can be manually changed in the limitador CR. For example replicas: If you do not specify replicas in the kuadrant CR, you can freely change replicas in the limitador CR. On the other hand, if you specify replicas in the kuadrant CR, let's say `3`, you can not change the value in limitador CR. The kuadrant controller will enforce limitador CR replicas to be `3`.

**Comment by jsmolar** [comment]
I am closing this one as this is the way we decided to go. I still belive that Kuadrant CR should have full control over Limitador CR.
