### ISSUE TITLE
Kuadrant CR is not removed when unregisterExternalAuthorizer fails

### ISSUE THREAD

**Issue by MStokluska** [Kuadrant/kuadrant-operator#697]
Giving Kuadrant a go I've noticed that the Kuadrant CR isn't removed if unregisterExternAuthorizer fails - in my case, it failed because it failed to locate smcp when Kuadrant CR was created/marked for deletion.

I think a small improvement in https://github.com/Kuadrant/kuadrant-operator/blob/release-v0.4.1/controllers/kuadrant_controller.go#L104 could be implemented.

**Comment by eguzki** [comment]
I think it was addressed in my PR about making istio optional: https://github.com/Kuadrant/kuadrant-operator/pull/645

Here https://github.com/Kuadrant/kuadrant-operator/pull/645/files#diff-53e20feafdf0308bc6f15e87b2dc63acd05e732a6bf70bc5247745edd59b1e4cR223-R226

Can you run latest (current `main`) operator and test? 

I think I found the same issue and I fixed. I wanted to make sure it is the same.

**Comment by MStokluska** [comment]
Thanks @eguzki - 
When trying the :latest tag I get following errors:
```
{"level":"info","ts":"2024-06-11T07:25:23Z","logger":"kuadrant-operator","msg":"go version: go1.21.11"}
{"level":"info","ts":"2024-06-11T07:25:23Z","logger":"kuadrant-operator","msg":"go os/arch: linux/amd64"}
{"level":"info","ts":"2024-06-11T07:25:23Z","logger":"kuadrant-operator","msg":"base logger","log level":"info","log mode":"production"}
flag provided but not defined: -config
Usage of /manager:
-health-probe-bind-address string
The address the probe endpoint binds to. (default ":8081")
-kubeconfig string
Paths to a kubeconfig. Only required if out-of-cluster.
-leader-elect
Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
-metrics-bind-address string
The address the metric endpoint binds to. (default ":8080")
```

Any ideas?

**Comment by eguzki** [comment]
mmm.... this is out of scope issue. I think that the deployment object of v0.4.1 is no longer compatible with the latest image. I suggest you remove the operator from Openshift and then just "make run" the operator locally (with oc session opened previously).

**Comment by eguzki** [comment]
Feel free to open if you can reproduce with latest image
