### ISSUE TITLE
TLSPolicy enforced status is wrongly true when secret is missing

### ISSUE THREAD

**Issue by azgabur** [Kuadrant/kuadrant-operator#704]
When TLSPolicy gets created a secret that contains the TLS key should be created by cert-manager. In case cert-manager operator is not working the secret will not be created. TLSPolicy will in this case still have status "Enforced: true" even though it is not true.

**Comment by pehala** [comment]
Similar thing happens when it takes a while to create secret (i.e. LetsEncrypt ACME validation), the TLSPolicy is enforced and all ready, but the secret is not present yet
