### ISSUE TITLE
Controller model: Gateway API Policies controllers

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/kuadrant-operator#719]
## Proposed model
![Controller model_ Gateway API Policies controllers(1)](https://github.com/Kuadrant/kuadrant-operator/assets/881529/627fe094-1302-4c0e-aa52-f036e9dec452)

**Comment by eguzki** [comment]
After thinking about this model and trying to apply to existing uses cases, I believe that there is no single pattern or controller model for all controllers dealing with Gateway API policies. 

On simple example to "break" the model: when there are broken paths in the Gateway API hierarchy, the mappers cannot scale up to the top type being reconciled. So, for instance, if you create a policy targeting a missing resource, the mapper cannot reach the gateway or kuadrant CR, so no reconciliation is created for the gateway or kuadrant CR, hence the policy status is never updated.

**Comment by eguzki** [comment]
cc @Boomatang

**Comment by Boomatang** [comment]
In general I do agree. The case of missing targets is a problem, which will happen. I can see the use of gitops where you can not guarantee the order of creation. The idea there is no single pattern to solve this could be very true. The `FOR` type on the RateLimitingPolicy is much simpler than the AuthPolicy as the Limitador CR is a one to many but the Authconfig CR is a one to one unless the defaults and overrides are used. 

I do not think we will be able to create a generalized solution to solve all the cases, without first solving the problem for the specific use case. 

There is a gut feel saying that using mappers on the FOR type might not be the best approach. For instance if Gateway is update or created I do not think that should map back to reconcile functions for any of the Policies that could be attached, but instead we reconcile the gateway. I know this would mean more controllers and possibly more complexity  with a controller, as the controller would have to handle all possible policies that  are attached to it. However that complexity is also triggered today with every policy controller triggering on gateway events.

**Comment by eguzki** [comment]
> There is a gut feel saying that using mappers on the FOR type might not be the best approach. For instance if Gateway is update or created I do not think that should map back to reconcile functions for any of the Policies that could be attached, but instead we reconcile the gateway. I know this would mean more controllers and possibly more complexity with a controller, as the controller would have to handle all possible policies that are attached to it. However that complexity is also triggered today with every policy controller triggering on gateway events.

That is the idea behind the concept: "target the top resource type out of the set of resources that impact on the thing you are reconciling. "
