### ISSUE TITLE
[WIP] Reconciled (sub)resources review

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/kuadrant-operator#724]

**Comment by guicassolato** [comment]
> Work being done in [Kuadrant Operator Reconciliation Workflow](https://docs.google.com/spreadsheets/d/1YkCsSXHrjWa3KxC1HaOIUfdmzxnLvyHIw8Q2PNFI_Lo/edit?gid=0#gid=0)

Thanks, @eguzki! More up to date ref: https://miro.com/app/board/uXjVKhAXwTY=/
