### ISSUE TITLE
RateLimitPolicy controller reconcile logic hardening

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/kuadrant-operator#74]
The ratelimitpolicy  API and how it is referenced by networking resources is constantly evolving. Doing hardening work sometimes is a waste of time, as the API or network references may change. As of today (HEAD is https://github.com/Kuadrant/kuadrant-controller/commit/8317588994e2cb36acda1caf801695050d41a135), I have detected some hardening work to be done in order to provide consistent UX when using the kuadrant API. Instead of working on those, as it may take quite time, I will drop here my findings and proposal for a robust reconciliation logic, covering all use cases. 

### Known issues

- [ ] RateLimitPolicy spec is not correctly reconciled. 
  - If you update, delete, create rate limit actions, the change will not take effect in associated envoy filters
  - If you delete limitador's rate limit entries, associated RateLimitCR's are not deleted. The implementation with the index in the name of the RateLimit CRs should be refactored to something that allows to identify ratelimit CRs with rate limit entries in the RLP
- [ ] Handle removal of the networking resources Virtual Service / HTTPRoute
  - When the VS is removed, the RLP controller gets a event. However, the controller tries to read the VS object and fails as it is not found. So the annotation to delete order is never deleted from the RLP and the "detaching from network" job is never done
- [ ] Watch for reconciled resources like AuthorizationPolicies, EnvoyFilters, RateLimits. If they are deleted or updated, the controller will be notified and react. The controller may allow changes or revert them back, depending on the policy implemented. 
- [ ] Reconcile when network resources (VS / HTTPRoute) update their gateway references.

### Proposal

Trying to follow the controller pattern, the RLP controller should be heavily refactored. The pattern tells us to read desired state, read existing state, then build (and execute) a list of actions to make the existing state look like the desired state. Always with the mindset of being idempotent, as the controller should expect reconciliation loops to happen even when the existing state is equal to the desired state.

The reconciliation of RateLimit objects is "simpler" as it depends entirely on the spec of the RLP object. However it still needs refactoring. The implementation with the index in the name of the RateLimit CRs should be refactored to something that allows to identify ratelimit CRs with rate limit entries in the RLP

Regarding the envoy filter reconciliation, it is more complex than the RateLimit objects. The envoy filter (EF) resource  is made up with information from the networking resource (Host and gateways) and information from the RLP spec. So, in order to catch all events that affect the `.spec` of the EF, the RLP controller should be watching for networking resources with a mapper function that converts events in the networking resources into RLP events using the annotation referencing the RLP object.

 On each RLP controller reconciliation event, the logic reconcile EF is:

* Build a list of networking resources having reference to the current RLP. 
  * This may imply client.List operations, so I suggest adding a kuadrant label to the networking resources to filter the list operation 
* With the list of networking resources (and associated Gateways), build a desired list of EnvoyFilters
* Read the list of EF resources created by the RLP controller. This is the "existing state".
  * This may require a label in the EF with a back reference to the RLP object, kind of "owner ref".
* Compare _existing_ list of EF with the _desired_ list of EF and create/execute a list of actions:
  * Create EF objects in _desired_ not in _existing_ 
  * Update EF objects in _desired_ and in _existing_ if they are different.  (The meaning of `equal` to be defined)
  * Delete EF objects in _existing_ and not in _desired_

**Comment by alexsnaps** [comment]
Would this be part of the gateway-api-machinery et al efforts?

**Comment by eguzki** [comment]
Yes and involves going through https://github.com/Kuadrant/architecture/issues/29

**Comment by eguzki** [comment]
The description is somehow outdated (it references to RLPv1 and currently we have RLPv2). (Un)fortunately, in essence, the claim is still valid.

**Comment by eguzki** [comment]
we can close this, outdated.
