### ISSUE TITLE
Configuration file should be added to allow for another way to run quickstart script without user prompt. 

### ISSUE THREAD

**Issue by ehearneRedHat** [Kuadrant/kuadrant-operator#755]
### What: 
A configuration file, to be stored as a `json` file and contains important variables/flags that `hack/quickstart-setup.sh` detects and runs the script without prompts . 

### How:
The configuration file could look like:

```json
{
   "key": "value",
   "key1": "value1"
}
```

And can include important details such as running in single cluster or multi cluster mode, which DNS Provider (if any) wants to be used, followed by DNS Provider specific env vars, etc. 

The script can check for a filename (maybe `conf.json`)  within a set location, such as `hack/`, or the script can check for a passed in/set variable (maybe `KUADRANT_CONF=<file>.json`). When it detects that file, it can read in the variables from quiet mode mentioned in https://github.com/Kuadrant/kuadrant-operator/issues/743 so that both modes offer equivalent functionality . 

This issue will need to be followed up by a docs write up explaining the new changes .

**Comment by pehala** [comment]
Why conf file? It feels needlesly complicated replacement for a proper CLI interface and ENV_VARS

**Comment by ehearneRedHat** [comment]
closed as redundant
