### ISSUE TITLE
Update to use the latest project sail

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#773]
When we last worked with Project Sail we pinned to a particular version of the operator. We need to make sure we are moving with the newer releases of project sail and remaining compatible as this will in time become an important way for users to install Istio as a gateway API provider

**Comment by adam-cattermole** [comment]
This is in progress here https://github.com/Kuadrant/kuadrant-operator/pull/696

**Comment by adam-cattermole** [comment]
PR is paused waiting for a helm chart to consume from the [v0.1 milestone](https://github.com/istio-ecosystem/sail-operator/milestone/1)

**Comment by adam-cattermole** [comment]
I believe an rc.1 release is now available so I'm going to update my PR and give this a go https://github.com/istio-ecosystem/sail-operator/releases/tag/0.1.0-rc.1

**Comment by maleck13** [comment]
When completing this work, we will need to update the OCP and kubernetes installation guides

**Comment by adam-cattermole** [comment]
Marking as done
