### ISSUE TITLE
Investigate transforming a route to a VirtualService

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#79]
If we were able to confidently transform an OpenShift Route with its various options into a Virtual Service, we could potentially contribute this transformation as part of the KCP control plane and the global load balancer.

**Done**

- [ ] map out a set of routes that cover the options provided by routes (TLS options and backend routing options)
- [ ] Look at what would be need to translate the options in the spec of a Route to a Virtual Service object.
- [ ] Highlight and identify any issues encountered during this translation

**Comment by alexsnaps** [comment]
@maleck13 Still relevant?
