### ISSUE TITLE
[state-of-the-world reconciler] Wasm module

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/kuadrant-operator#817]
Configure the wasm module integration for supported Gateway API providers.

**Comment by eguzki** [comment]
this is already happening, isn't it? @guicassolato

**Comment by guicassolato** [comment]
> this is already happening, isn't it? @guicassolato

For the Rate Limit part, yes.

**Comment by eguzki** [comment]
I think we can close this issue. The integration with Istio and EnvoyGateway using a wasm module is already done. 

**How** we use this integration is covered in https://github.com/Kuadrant/kuadrant-operator/issues/822, so this issue is done.
