### ISSUE TITLE
[state-of-the-world reconciler] Effective policy DNS

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/kuadrant-operator#818]
Reconciliation of effective policies for DNS. Creation of DNSRecords for each applicable path in the topology graph (TBD: Gateway or Gateway → Gateway Listener).

**Comment by maleck13** [comment]
@mikenairn this may already be covered under the work your doing not sure. @guicassolato assigned to DNS area , is it something sepcific to DNS?
