### ISSUE TITLE
[state-of-the-world reconciler] Topology ConfigMap

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/kuadrant-operator#831]
Reconciliation of the topology graph represented in DOT language stored into a read-only ConfigMap resource.

**Comment by guicassolato** [comment]
@jasonmadigan, can you please confirm if a ConfigMap is OK for storing the topology graph given the applications in sight for it?

We had discussed off-line about defining a new CRD for storing the topology graph. In the last community call, it was proposed to use a ConfigMap instead, to avoid the burden of managing yet another CRD.

**Comment by jasonmadigan** [comment]
@guicassolato config-map works for me, would be just as accessible
