### ISSUE TITLE
Re-evaluate integration tests for DNSPolicy

### ISSUE THREAD

**Issue by maksymvavilov** [Kuadrant/kuadrant-operator#889]
## What
This issue was born from a discussion on the endpoints API [PR](https://github.com/Kuadrant/kuadrant-operator/pull/799). We have delegated the generation of endpoints to the `dns-operator`, which begs the question: do we keep testing for correctly generated endpoints in `kuadrant-operator`? 

Right now we are checking for "we generated correct endpoints" twice: in the `dns-operator` at the [unit test ](https://github.com/Kuadrant/dns-operator/blob/main/pkg/builder/endpoints_test.go) and in the `kuadrant-operator` as the [integration test](https://github.com/Kuadrant/kuadrant-operator/blob/main/tests/common/dnspolicy/dnspolicy_controller_single_cluster_test.go).  Booth suites test for the same use cases. 

## How 
There could be several possible outcomes: 
1. We drop testing for correctly generated endpoints and delegate this responsibility to the `dns-operator`. This will reduce the number of tests for the `kuadrant-operator` and make them solely focused on the DNSPolicy — a [WIP PR](https://github.com/Kuadrant/kuadrant-operator/pull/882) for this.   
2. We keep booth suites but stop updating `kuadrant-operator` with new use cases. It potentially might be an issue if we decide to introduce a breaking change to the endpoints generation API in the `dns-operator`.  That is if we keep targeting main of the `dns-operator`. 
3. We keep both and have `kuadrant-operator` to define a set of "happy path" tests (e.g. one of lb strategy and one of simple) and have "all the tests" in the `dns-operator`. This will keep `kuadrant-controller`. It still might have the issue of the "breaking change to the API".

**Comment by philbrookes** [comment]
The tests are currently executed in the desired manner.
