### ISSUE TITLE
Investigate supporting defaults and overrides in AuthPolicy

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#91]
**Use Case**

As a gateway administrator I want to lock down access to any host attaching to this gateway. By default I want to apply a default DENY ALL policy at the gateway level. 
When a policy is created targeting a HTTPRoute, I want that policy to then take precedence over my default policy. 

- [ ] Validate the existing behaviour supports this use case
- [ ] Move authschema to default
- [ ] Create a Demo showing two services and default policy. Show how access is only allowed when a policy has been defined

**Comment by guicassolato** [comment]
Superseded by https://github.com/Kuadrant/kuadrant-operator/issues/431
