### ISSUE TITLE
Generate route conditions into the wasm config in CEL

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/kuadrant-operator#979]

**Comment by eguzki** [comment]
I think I am addressing this in https://github.com/Kuadrant/kuadrant-operator/pull/976

I wanted to leverage only CEL capabilites from the Wasm configuration. That lead me to write the code. It is not much.

**Comment by guicassolato** [comment]
I've seen this addressed in https://github.com/Kuadrant/kuadrant-operator/pull/971.
